# Generated by Django 5.1.7 on 2025-03-26 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionOrdonnancesapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicament',
            name='date_expiration',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='laboratoire',
        ),
        migrations.AddField(
            model_name='medicament',
            name='disponibilite',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='duree_traitement',
            field=models.IntegerField(default=7, help_text='Durée du traitement en jours'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='effets',
            field=models.ManyToManyField(blank=True, related_name='medicaments_relations', to='gestionOrdonnancesapp.effet'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='interactions',
            field=models.ManyToManyField(blank=True, related_name='interactions_medicamenteuses', to='gestionOrdonnancesapp.medicament'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='prix',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='medicament',
            name='voie_administration',
            field=models.CharField(choices=[('Orale', 'Orale'), ('Injectable', 'Injectable'), ('Topique', 'Topique'), ('Inhalée', 'Inhalée'), ('Sublinguale', 'Sublinguale'), ('Rectale', 'Rectale')], default='Orale', max_length=50),
        ),
        migrations.AlterField(
            model_name='effet',
            name='medicaments',
            field=models.ManyToManyField(related_name='effets_secondaires', to='gestionOrdonnancesapp.medicament'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='molecule_active',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RenameModel(
            old_name='Ordannance',
            new_name='Ordonnance',
        ),
        migrations.CreateModel(
            name='MedicamentOrdonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posologie', models.TextField()),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances_medicamenteuses', to='gestionOrdonnancesapp.medicament')),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaments_prescrits', to='gestionOrdonnancesapp.ordonnance')),
            ],
        ),
    ]
