# Generated by Django 5.1.7 on 2025-03-17 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionOrdonnancesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('M', 'Médecin'), ('P', 'Patient')], max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(limit_choices_to={'role__in': ['P', 'M']}, on_delete=django.db.models.deletion.CASCADE, to='gestionOrdonnancesapp.role'),
        ),
    ]
