# Generated by Django 5.1.7 on 2025-03-28 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionOrdonnancesapp', '0002_user_qr_code_alter_role_role_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('gravite', models.CharField(choices=[('Légère', 'Légère'), ('modérée', 'modérée'), ('sévère', 'sévère')], max_length=100)),
                ('symptomes', models.TextField()),
                ('traitement', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='cin',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='DossierMedicale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('bloodType', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, null=True)),
                ('tension', models.CharField(max_length=255)),
                ('maladieChronique', models.TextField(blank=True, null=True)),
                ('antecedentsChirurgicaux', models.TextField(blank=True, null=True)),
                ('contactUrgence', models.CharField(blank=True, max_length=255, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('miseAJour', models.DateTimeField(auto_now=True)),
                ('allergies', models.ManyToManyField(blank=True, related_name='dossiers_medicaux', to='gestionOrdonnancesapp.allergie')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_medical', to='gestionOrdonnancesapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('medicine_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=255)),
                ('dossierMedicale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='gestionOrdonnancesapp.dossiermedicale')),
            ],
        ),
    ]
