# Generated by Django 5.1.7 on 2025-04-02 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionOrdonnancesapp', '0002_remove_medicament_date_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cin',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(limit_choices_to={'role__in': ['P', 'M']}, on_delete=django.db.models.deletion.CASCADE, to='gestionOrdonnancesapp.role'),
        ),
    ]
