# Generated by Django 5.1.7 on 2025-03-28 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionOrdonnancesapp', '0003_allergie_alter_user_cin_dossiermedicale_ordonnance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossiermedicale',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='dossiermedicale',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='ordonnance',
            name='dossierMedicale',
        ),
        migrations.DeleteModel(
            name='Allergie',
        ),
        migrations.DeleteModel(
            name='DossierMedicale',
        ),
        migrations.DeleteModel(
            name='Ordonnance',
        ),
    ]
