# Generated by Django 5.1.7 on 2025-04-02 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionOrdonnancesapp', '0002_remove_medicament_date_expiration_and_more'),
        ('gestionOrdonnancesapp', '0004_remove_dossiermedicale_allergies_and_more'),
    ]

    operations = [
    ]
